apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bran-dev
  namespace: argocd
  labels:
    app: bran
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/akash202k/cncf_kubetux_deployments  # Update this
    path: deployments/helm-charts/bran
    targetRevision: HEAD
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cncf-bran
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    
  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas