# Application Configuration
app:
  name: hodr
  namespace: cncf-hodr

# Image Configuration
image:
  repository: public.ecr.aws/o9l3s9p6/cncf-hodr
  tag: v1.0.1
  pullPolicy: IfNotPresent

# Service Configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Deployment Configuration
deployment:
  replicaCount: 1
  
# Resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

# HPA Configuration
hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

# Ingress Configuration
ingress:
  host: akashpawar.com
  certificateArn: 'arn:aws:acm:us-east-1:187483722928:certificate/8e26563d-51e2-4467-b732-fe3b9bbccb0f'
  loadBalancerName: cncf-alb
  groupName: cncf-shared

# Health Check Configuration
healthCheck:
  path: /hodr/metrics
  port: 8080


# Network Policy Configuration
networkPolicy:
  enabled: true
  
  # What hodr can connect TO (RESTRICTIVE egress)
  allowEgress:
    toDNS: true                      # Allow DNS resolution
    toExternal: true                 # Allow external API calls
    toMonitoring: false              # Block monitoring if not needed
    # toBran: false                  # EXPLICITLY NOT ALLOWED (omitted = blocked)